#!/usr/bin/env bash
# Post (or update) a benchmark summary as a sticky PR comment. A hidden marker
# lets repeat runs update the same comment in place.
#
# Usage: post-bench-comment.sh [comparison.md] [full-results.md]
# With no comparison file, posts a status-only comment (e.g. a failure notice)
# that updates the same sticky comment in place via the shared marker.
# Env: PR_NUMBER, GH_REPO, GH_TOKEN (required to post); JOB_URL, DASHBOARD_URL,
#      ACTOR, CONFIG, STATUS_PREFIX, COMMENT_KEY (default foundry-bench),
#      DRY_RUN (print only).
set -euo pipefail

COMPARISON_MD="${1:-}"
FULL_MD="${2:-}"
STATUS_PREFIX="${STATUS_PREFIX:-✅ Benchmark complete!}"

if [ -n "$COMPARISON_MD" ] && [ ! -f "$COMPARISON_MD" ]; then
    echo "error: comparison markdown missing: '$COMPARISON_MD'" >&2
    exit 2
fi

COMMENT_KEY="${COMMENT_KEY:-foundry-bench}"
MARKER="<!-- foundry-bench-report:${COMMENT_KEY} -->"

# Assemble the comment body.
BODY_FILE="$(mktemp)"
trap 'rm -f "$BODY_FILE"' EXIT

{
    printf '%s\n' "$MARKER"
    printf '## 📊 Benchmark Results\n\n'

    if [ -n "${ACTOR:-}" ]; then
        printf 'cc @%s\n\n' "$ACTOR"
    fi

    links=""
    if [ -n "${JOB_URL:-}" ]; then
        links="[View job](${JOB_URL})"
    fi
    if [ -n "${DASHBOARD_URL:-}" ]; then
        [ -n "$links" ] && links="${links} · "
        links="${links}[Dashboard run](${DASHBOARD_URL})"
    fi
    if [ -n "$links" ]; then
        printf '%s %s\n\n' "$STATUS_PREFIX" "$links"
    else
        printf '%s\n\n' "$STATUS_PREFIX"
    fi

    if [ -n "${CONFIG:-}" ]; then
        # shellcheck disable=SC2016  # backticks are literal Markdown, not shell.
        printf '<sub>Config: `%s`</sub>\n\n' "$CONFIG"
    fi

    if [ -n "$COMPARISON_MD" ]; then
        cat "$COMPARISON_MD"
        printf '\n'

        if [ -n "$FULL_MD" ] && [ -f "$FULL_MD" ]; then
            printf '\n<details>\n<summary>📈 Full benchmark results</summary>\n\n'
            cat "$FULL_MD"
            printf '\n</details>\n'
        fi
    fi

    printf '\n---\n<sub>🤖 Generated by the Foundry Benchmarks workflow.</sub>\n'
} > "$BODY_FILE"

if [ "${DRY_RUN:-}" = "1" ]; then
    cat "$BODY_FILE"
    exit 0
fi

: "${PR_NUMBER:?PR_NUMBER is required}"
: "${GH_REPO:?GH_REPO is required}"

# Upsert: edit our own previous marked comment, else create. Restricting to the
# bot's comments prevents hijacking a comment that merely quotes the marker.
existing_id="$(
    gh api --paginate "repos/${GH_REPO}/issues/${PR_NUMBER}/comments" \
        --jq ".[] | select(.user.type == \"Bot\") | select(.body | contains(\"${MARKER}\")) | .id" \
        | head -n1
)"

if [ -n "$existing_id" ]; then
    gh api --method PATCH "repos/${GH_REPO}/issues/comments/${existing_id}" \
        -F body=@"$BODY_FILE" >/dev/null
    echo "Updated existing benchmark comment (#${existing_id})."
else
    gh api --method POST "repos/${GH_REPO}/issues/${PR_NUMBER}/comments" \
        -F body=@"$BODY_FILE" >/dev/null
    echo "Created benchmark comment on PR #${PR_NUMBER}."
fi
